##
## EPITECH PROJECT, 2020
## Arcade - Game
## File description:
## Makefile
##

DIR_NIBBLER = ./nibbler/

all:
	make -C $(DIR_NIBBLER)

clean:
	make -C $(DIR_NIBBLER) clean

fclean: clean
	make -C $(DIR_NIBBLER) fclean

re: fclean all

debug:
	make -C $(DIR_NIBBLER) debug

.PHONY:	all clean fclean re debug